import signIn from './images/pablo-sign-in 1.png'
import lendsqrLogo from './icons/logo.svg'
import user1 from './images/user1.png'
import searchIcon from './icons/searchIcon.png'
import notificationIcon from './icons/notification.png'
import dropdownIcon from './icons/dropdownIcon.png'
import briefcaseIcon from './icons/briefcase 1.png'
import dropdownIcon2 from './icons/np_next_2236826_000000 2.png'
import homeIcon from './icons/home 1.png'
import usersIcon from './icons/users 1.png'
import usersIcon2 from './icons/user-friends 1.png'
import loansIcon from './icons/sack 1.png'
import handshakeIcon from './icons/handshake-regular 1.png'
import piggybankIcon from './icons/piggy-bank 1.png'
import handshakeIcon2 from './icons/Group 104.png'
import usersIcon3 from './icons/user-check 1.png'
import usersIcon4 from './icons/user-times 1.png'
import bankIcon from './icons/np_bank_148501_000000 1.png'
import coinsIcon from './icons/coins-solid 1.png'
import orgIcon from './icons/icon.png'
import galaxyIcon from './icons/galaxy 1.png'
import usersIcon5 from './icons/user-cog 1.png'
import scrollIcon from './icons/scroll 1.png'
import chartbarIcon from './icons/chart-bar 2.png'
import slidersIcon from './icons/sliders-h 1.png'
import badgeIcon from './icons/badge-percent 1.png'
import clipboardIcon from './icons/clipboard-list 1.png'
import ellipse from './icons/ellipse.png'
import goldstarIcon from './icons/np_star_1208084_000000 1.png'
import starIcon from './icons/np_star_1171151_000000 1.png'
import logoutIcon from './icons/sign-out 1.png'
import backarrowIcon from './icons/np_back_3007750_000000 1.png'
import unionIcon from './icons/Union.png'
import filterIcon from './icons/filter.png'
import doubleUserIcon from './icons/double-user.png'
import trippleUserIcon from './icons/tripple-user.png'
import documentIcon from './icons/document.png'
import dbIcon from './icons/db.png'
import loginIllustrationImg from './images/loginIllustration.png'
import viewIcon from './icons/np_view_1214519_000000 1.png'
import blackListIcon from './icons/np_delete-friend_3248001_000000 1.png'
import usersIcon6 from './icons/np_user_2995993_000000 1.png'



export {loginIllustrationImg, signIn, lendsqrLogo, user1, searchIcon, notificationIcon, dropdownIcon, dropdownIcon2, briefcaseIcon, homeIcon, usersIcon, usersIcon2, loansIcon, handshakeIcon, piggybankIcon, handshakeIcon2, usersIcon3, usersIcon4, bankIcon, coinsIcon, orgIcon, galaxyIcon, usersIcon5, scrollIcon, chartbarIcon, slidersIcon, badgeIcon, clipboardIcon, ellipse, goldstarIcon, starIcon, logoutIcon, backarrowIcon, unionIcon, filterIcon, doubleUserIcon, trippleUserIcon, documentIcon, dbIcon, viewIcon, blackListIcon, usersIcon6 }