import signIn from './pablo-sign-in.png'
import lendsqrLogo from './logo.svg'
import user1 from './user1.png'
import searchIcon from './searchIcon.png'
import notificationIcon from './notification.png'
import dropdownIcon from './dropdownIcon.png'
import briefcaseIcon from './briefcase 1.png'
import dropdownIcon2 from './np_next_2236826_000000 2.png'
import homeIcon from './home 1.png'
import usersIcon from './users 1.png'
import usersIcon2 from './user-friends 1.png'
import loansIcon from './sack 1.png'
import handshakeIcon from './handshake-regular 1.png'
import piggybankIcon from './piggy-bank 1.png'
import handshakeIcon2 from './Group 104.png'
import usersIcon3 from './user-check 1.png'
import usersIcon4 from './user-times 1.png'
import bankIcon from './np_bank_148501_000000 1.png'
import coinsIcon from './coins-solid 1.png'
import orgIcon from './icon.png'
import galaxyIcon from './galaxy 1.png'
import usersIcon5 from './user-cog 1.png'
import scrollIcon from './scroll 1.png'
import chartbarIcon from './chart-bar 2.png'
import slidersIcon from './sliders-h 1.png'
import badgeIcon from './badge-percent 1.png'
import clipboardIcon from './clipboard-list 1.png'


export { signIn, lendsqrLogo, user1, searchIcon, notificationIcon, dropdownIcon, dropdownIcon2, briefcaseIcon, homeIcon, usersIcon, usersIcon2, loansIcon, handshakeIcon, piggybankIcon, handshakeIcon2, usersIcon3, usersIcon4, bankIcon, coinsIcon, orgIcon, galaxyIcon, usersIcon5, scrollIcon, chartbarIcon, slidersIcon, badgeIcon, clipboardIcon }