import signIn from './pablo-sign-in 1.png'
import lendsqrLogo from './logo.svg'
import user1 from './user1.png'
import searchIcon from './searchIcon.png'
import notificationIcon from './notification.png'
import dropdownIcon from './dropdownIcon.png'
import briefcaseIcon from './briefcase 1.png'
import dropdownIcon2 from './np_next_2236826_000000 2.png'
import homeIcon from './home 1.png'
import usersIcon from './users 1.png'
import usersIcon2 from './user-friends 1.png'
import loansIcon from './sack 1.png'
import handshakeIcon from './handshake-regular 1.png'
import piggybankIcon from './piggy-bank 1.png'
import handshakeIcon2 from './Group 104.png'
import usersIcon3 from './user-check 1.png'
import usersIcon4 from './user-times 1.png'
import bankIcon from './np_bank_148501_000000 1.png'
import coinsIcon from './coins-solid 1.png'
import orgIcon from './icon.png'
import galaxyIcon from './galaxy 1.png'
import usersIcon5 from './user-cog 1.png'
import scrollIcon from './scroll 1.png'
import chartbarIcon from './chart-bar 2.png'
import slidersIcon from './sliders-h 1.png'
import badgeIcon from './badge-percent 1.png'
import clipboardIcon from './clipboard-list 1.png'
import ellipse from './ellipse.png'
import goldstarIcon from './np_star_1208084_000000 1.png'
import starIcon from './np_star_1171151_000000 1.png'
import logoutIcon from './sign-out 1.png'
import backarrowIcon from './np_back_3007750_000000 1.png'
import unionIcon from './Union.png'
import filterIcon from './filter.png'
import doubleUserIcon from './double-user.png'
import trippleUserIcon from './tripple-user.png'
import documentIcon from './document.png'
import dbIcon from './db.png'
import loginIllustrationImg from './loginIllustration.png'
import viewIcon from './np_view_1214519_000000 1.png'
import blackListIcon from './np_delete-friend_3248001_000000 1.png'
import usersIcon6 from './np_user_2995993_000000 1.png'



export {loginIllustrationImg, signIn, lendsqrLogo, user1, searchIcon, notificationIcon, dropdownIcon, dropdownIcon2, briefcaseIcon, homeIcon, usersIcon, usersIcon2, loansIcon, handshakeIcon, piggybankIcon, handshakeIcon2, usersIcon3, usersIcon4, bankIcon, coinsIcon, orgIcon, galaxyIcon, usersIcon5, scrollIcon, chartbarIcon, slidersIcon, badgeIcon, clipboardIcon, ellipse, goldstarIcon, starIcon, logoutIcon, backarrowIcon, unionIcon, filterIcon, doubleUserIcon, trippleUserIcon, documentIcon, dbIcon, viewIcon, blackListIcon, usersIcon6 }